- project:
    check:
      jobs:
        - linters
    gate:
      jobs:
        - linters
    post:
      debug: True
      jobs:
        - noop
    release:
      debug: True
      jobs:
        - noop
